FROM ubuntu:latest
#installing less command to read dockerfile1.txt
RUN apt-get update && \
    apt-get upgrade -y \
    less
WORKDIR /app4/
COPY . /app4/
CMD "echo"  "do check the app folder to find the file"